In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.3'

# Basic Concepts of ndarray

N-dimentional array (or ndarray) 是 NumPy 的主要物件。

ndarray 可使用 `np.array()` 建立。

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6.1]]) # 
x

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6.1]])

In [4]:
# shape 為 ndarray 的維度
x.shape 

(2, 3)

In [5]:
# reshape() 可以改變維度
x.reshape(1, 6) 

array([[ 1. ,  2. ,  3. ,  4. ,  5. ,  6.1]])

In [6]:
# dtype 為 ndarray 存放的物件型態
x.dtype 

dtype('float64')

ndarray 的物件種類可見[文件](https://docs.scipy.org/doc/numpy/user/basics.types.html)。

In [7]:
int_a = np.array([1, 2, 3], dtype=int)

In [8]:
int_a.dtype

dtype('int64')

In [9]:
# astype() 可轉換型態
float_a = int_a.astype('float64') 

In [10]:
float_a.dtype

dtype('float64')

## 更多產生 ndarray 的方式

In [11]:
# np.arange(n1, n2) 會產生閉開區間，即 n1 到 n2 - 1
np.array(np.arange(1, 100)) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
# np.random.randn() 可產生標準常態分配的亂數
np.random.randn(3, 2) 

array([[ 0.15994494,  0.52017142],
       [ 0.88308704, -1.8121989 ],
       [-0.72296634,  0.84060981]])

In [13]:
# np.linspace(a, b, n) 可產生 n 個均分 [a, b] 的值
np.linspace(0, 1, 5) 

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [14]:
# np.full((m, n), fill_value) 可回傳維度 mxn, 且值接為 fill_value 的 ndarray
np.full((2, 2), fill_value=1.8) 

array([[ 1.8,  1.8],
       [ 1.8,  1.8]])

In [15]:
# np.ones(n) 可產生 1xn, 且全為 1 的 ndarray 
np.ones(10) 

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
# np.zeros(n) 可產生 1xn, 且全為 0 的 ndarray 
np.zeros(10) 

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [17]:
# np.eye(n) 可產生 nxn 的單位矩陣 (參數 k 可調整對角線位置)
np.eye(3) 

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [18]:
# np.identity 可產生 nxn 的單位矩陣
np.identity(3) 

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# Array Manipulations

以下說明三種基本的 array 操作：
1. 取值與取值並更新 (Filtering and updating values)
2. 變換維度 (Transforming the shape of an array)
3. 排序(Sorting an array)

## ndarray 取值

### 使用 Basic Index 取值

In [19]:
# 1 維的 array 取值的方法跟 python list 相似
x = np.array(np.arange(10))
x[0] # index starts at 0

0

In [20]:
x[1:5] # 1:5 一樣是閉開區間 

array([1, 2, 3, 4])

In [21]:
x[-1] 

9

In [22]:
x[2:] # index 為 2 到最後一個的元素

array([2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[:3] # index 為 0 到 2 的元素

array([0, 1, 2])

In [24]:
# 2維以上的取值方式: 1. 逗號, 2. [][], 兩者回傳結果可能會不同
arr = np.array(np.arange(9)).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
# 取單一值會相同
arr[2, 1] == arr[2][1]

True

In [26]:
# 取多個值可能會不同
arr[0:2, 1] # 取出第一列與第二列的第二個元素

array([1, 4])

In [27]:
arr[0:2][1] # 取出第一列與第二列後，再取出第二列

array([3, 4, 5])

In [28]:
arr[[-2, -3]] # 取出倒數第二列跟倒數第三列

array([[3, 4, 5],
       [0, 1, 2]])

In [29]:
# 使用 take() 搭配 index list 取值
idx = [7, 1, 5]
arr = np.arange(10)
arr.take(idx)

array([7, 1, 5])

### 使用 Boolean Index 取值

In [30]:
val = np.array(np.arange(10))
val > 5 

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [31]:
val[val > 5] # 回傳 a 大於 5 的元素

array([6, 7, 8, 9])

In [32]:
names = np.array(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])

In [33]:
val[names == "b"]

array([1])

In [34]:
val[~(names == "b")] # 用 ~ 取否

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
val[(names == "b") | (names == "g")]

array([1, 6])

### 更新 ndarray 值
先取值，再指定新值

In [36]:
arr = np.arange(9)
arr[[1, 5, 8]] = 10
arr

array([ 0, 10,  2,  3,  4, 10,  6,  7, 10])

In [37]:
arr[arr > 5] = 3
arr

array([0, 3, 2, 3, 4, 3, 3, 3, 3])

In [38]:
arr[[2, 4, 6]] = [10, 20, 30]
arr

array([ 0,  3, 10,  3, 20,  3, 30,  3,  3])

In [39]:
# 使用 put() 搭配 index list 更新值
idx = [0, 5, 8]
arr.put(idx, 40)
arr

array([40,  3, 10,  3, 20, 40, 30,  3, 40])

## 變換維度

In [40]:
arr = np.array(np.arange(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# 透過 np.newaxis 回傳列向量
arr[:, np.newaxis] 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [42]:
arr = np.array(np.arange(32)).reshape(4, 8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [43]:
# .T 可以進行轉置(Transpose)
arr.T 

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [44]:
# swapaxes() 也可以做維度交換
arr.swapaxes(0, 1) 

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [45]:
# 若參數設定 -1 ，則程式會自動推斷。但只能有一個維度設定為 -1
arr = np.arange(15)
arr.reshape(-1, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [47]:
## 透過 flatten() 或 ravel() 變成 1xn array
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
arr.ravel('F') # 'F' (Fortran) 的順序是行先於列

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

## 排序

排序 array 有下面兩個函數：
1. `np.sort()`：不會改變原本的 ndarray
2. `ndarray.sort()`：會改變原本的 ndarray

In [50]:
x = np.random.randint(1, 10, 5)
x

array([8, 6, 4, 7, 8])

In [51]:
np.sort(x)

array([4, 6, 7, 8, 8])

In [52]:
x

array([8, 6, 4, 7, 8])

In [53]:
x.sort()
x

array([4, 6, 7, 8, 8])

In [54]:
# 若 array 有多個維度，設定 axis 參數可決定沿著哪個維度排序
X = np.random.randn(12).reshape(3, 4)
X

array([[-1.27456788, -1.7868395 , -0.70257809,  0.67107081],
       [ 0.24137929, -1.67477285, -4.02809458, -0.8949762 ],
       [ 0.4433829 , -0.73401221, -0.4376402 , -1.56305951]])

In [55]:
np.sort(X, axis=0) # column

array([[-1.27456788, -1.7868395 , -4.02809458, -1.56305951],
       [ 0.24137929, -1.67477285, -0.70257809, -0.8949762 ],
       [ 0.4433829 , -0.73401221, -0.4376402 ,  0.67107081]])

In [56]:
np.sort(X, axis=1) # row

array([[-1.7868395 , -1.27456788, -0.70257809,  0.67107081],
       [-4.02809458, -1.67477285, -0.8949762 ,  0.24137929],
       [-1.56305951, -0.73401221, -0.4376402 ,  0.4433829 ]])

In [57]:
X.sort(axis=0)
X

array([[-1.27456788, -1.7868395 , -4.02809458, -1.56305951],
       [ 0.24137929, -1.67477285, -0.70257809, -0.8949762 ],
       [ 0.4433829 , -0.73401221, -0.4376402 ,  0.67107081]])

In [58]:
# ndarray[:, ::-1] 可回傳 descending 形式
X[:, ::-1]

array([[-1.56305951, -4.02809458, -1.7868395 , -1.27456788],
       [-0.8949762 , -0.70257809, -1.67477285,  0.24137929],
       [ 0.67107081, -0.4376402 , -0.73401221,  0.4433829 ]])

## Indirect Sorts: argsort and lexsort

`argsort()` 透過其他 keys 間接進行排序，而非直接使用值排序。

In [59]:
values = np.array([4, 1, 0, 3, 2])
arr = np.random.randn(3, 5)
arr[0] = values
arr

array([[ 4.        ,  1.        ,  0.        ,  3.        ,  2.        ],
       [-0.2599273 , -0.38472753,  0.43935061, -0.61040463, -0.01912704],
       [-0.0099046 ,  1.28920045,  0.41719876, -0.33952618, -0.89980111]])

In [60]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 0.43935061, -0.38472753, -0.01912704, -0.61040463, -0.2599273 ],
       [ 0.41719876,  1.28920045, -0.89980111, -0.33952618, -0.0099046 ]])

# Universal Functions (ufunc)

Universal functions 為 NumPy 中的向量化 (vectorized) 函數，也就是這些函數可一次直接作用到整個 ndarray，不需要使用 for 迴圈。

In [61]:
arr = np.array(np.arange(10))

In [62]:
# 對 ndarray 開平方，不需要 for 迴圈
np.sqrt(arr) 

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [63]:
np.square(np.sqrt(arr))

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [64]:
# 亦有可作用到兩個 ndarrays 的 ufunc (稱為 binary ufunc)
# np.random.random() 產生 [0.0, 1.0) 間亂數，不要跟 np.random.randn() 混淆
x = np.random.random(10) 
y = np.random.random(10)
np.maximum(x, y) # 兩兩比較，取出值較大者

array([ 0.2991295 ,  0.82438444,  0.32236037,  0.92940592,  0.5169563 ,
        0.98853813,  0.30174558,  0.40465374,  0.62671385,  0.66888643])

In [65]:
x + y # 亦可直接作加減乘除

array([ 0.53689156,  1.16993166,  0.53069724,  1.82029143,  0.5364132 ,
        1.26773582,  0.52989099,  0.78088917,  0.93907134,  1.16966455])

In [66]:
np.sqrt(x ** 2 + y ** 2)

array([ 0.38211157,  0.89387504,  0.38382348,  1.28742858,  0.51732233,
        1.02720932,  0.37828656,  0.55253755,  0.70024099,  0.83557631])

In [67]:
# where() 是向量化的 if-else
x = np.random.randn(10)
np.where(x > 0, 1, -1)

array([-1,  1, -1, -1, -1, -1,  1,  1, -1, -1])

善用 universal functions 會比使用迴圈更快速且簡潔。 ufunc 的整理可見[文件](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)。

Binary ufuncs 之所以能運作，主要是 NumPy 物件有所謂的 *Broadcasting* 性質。如以下的例子，可想成 5 被 broadcasted，直接被乘到 x 的每一元素。

In [68]:
X = np.random.random(9).reshape(3, 3)
X * 5

array([[ 0.92711602,  0.54684534,  2.56617863],
       [ 0.54120354,  4.71725077,  4.26196406],
       [ 4.42987007,  1.60093459,  0.66427932]])

Binary ufuncs 的 *Broadcasting* 的運作規則如下三條:
 1. 維度較小的 ndarray 會在由從左邊維度補 1 ，直到兩個維度相等。
 2. 若兩者 shape 不符，且其中有一個 ndarray 的 shape 內的值為 1，將 1 變成另一個 ndarray 對應位置的值。 
 3. 若兩者 shape 不符，且沒有任一個 ndarray 的 shape 內的值為 1，回傳錯誤。

如以下的例子，x.shape 為 (3, 2), y.shape 為 (2, )。
- 當兩者相加時，y 的 shape 依規則 1 會先變成 (1, 2)。
- 接著依規則 2，(1, 2) 裡的 1 會變成對應 x 第一個位置的 3，因此 y 的 shape 變成 (3, 2)。
- 兩者維度相符，故可直接相加。

In [69]:
x = np.arange(6).reshape(3, 2)
y = np.arange(2)

In [70]:
x.shape

(3, 2)

In [71]:
y.shape

(2,)

In [72]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [73]:
y

array([0, 1])

In [74]:
# 使用規則 2 時，可想成原本一列 [0, 1] 變成三列 [0, 1]
y2 = np.array([y, y, y])
y2

array([[0, 1],
       [0, 1],
       [0, 1]])

In [75]:
x + y

array([[0, 2],
       [2, 4],
       [4, 6]])

In [76]:
x + y2

array([[0, 2],
       [2, 4],
       [4, 6]])

## Example: Standardize an Array
以下的例子說明如何使用 Broadcasting 進行矩陣的標準化。

In [77]:
X = np.random.random(12).reshape(3, 4)
X

array([[ 0.35529937,  0.53758193,  0.49291303,  0.98905762],
       [ 0.037363  ,  0.50883722,  0.92198304,  0.8508942 ],
       [ 0.96056349,  0.90369899,  0.75032113,  0.8158663 ]])

In [78]:
X

array([[ 0.35529937,  0.53758193,  0.49291303,  0.98905762],
       [ 0.037363  ,  0.50883722,  0.92198304,  0.8508942 ],
       [ 0.96056349,  0.90369899,  0.75032113,  0.8158663 ]])

In [79]:
# 求算每行 (column) 的平均數 (axis=0)
X_mean = X.mean(axis=0)
X_mean

array([ 0.45107529,  0.65003938,  0.72173907,  0.88527271])

In [80]:
# 求算每行 (column) 的標準差 (axis=0)
X_std = X.std(axis=0)
X_std

array([ 0.38293129,  0.1797479 ,  0.17632918,  0.07476728])

In [81]:
X_scaled = (X - X_mean) / X_std
X_scaled

array([[-0.25011253, -0.62563984, -1.29772075,  1.38810602],
       [-1.08038257, -0.78555665,  1.13562586, -0.45980686],
       [ 1.3304951 ,  1.41119649,  0.1620949 , -0.92829916]])

In [82]:
X_scaled.mean(0)

array([  1.48029737e-16,   4.44089210e-16,   6.38378239e-16,
         4.81096644e-16])

In [83]:
X_scaled.std(0)

array([ 1.,  1.,  1.,  1.])

## Statistical Methods
統計彙整函數也是 ufuncs，如前段的 `mean()`, `std()`。其他的統計函數可見[文件](https://docs.scipy.org/doc/numpy/reference/routines.statistics.html)

In [84]:
# 使用 average() 求算加權平均數
X = np.random.randint(low=1, high=10, size=5,)
weights = [2, 2, 2, 3, 1]

In [85]:
np.average(X, weights=weights)

6.0999999999999996

In [86]:
# 使用 sum() 計算符合條件的個數
X = np.random.randn(50)
(X > 0).sum()

25

In [87]:
# 有些函數有 nan 版本，可以忽略 NaNs
X = np.append(np.random.randint(1, 10, 5), np.nan)
np.nanmean(X)

5.2000000000000002

## Methods for Boolean Arrays
 - any() 可用來檢查是否有元素符合條件
 - all() 可用來所有元素是否都符合條件

In [88]:
X = np.random.randn(50)

In [89]:
np.any(X > 0)

True

In [90]:
np.all(X > 0)

False

## Custom ufuncs
若要使用自訂函數，可透過 np.frompyfunc() 或 np.vectorize()。

In [91]:
def add_elements(x, y):
    return(x + y)

add_two_arrays = np.frompyfunc(add_elements, 2, 1) # 2 表示輸入參數個數，1 表示輸出參數個數
add_two_arrays(np.arange(3), np.arange(3))

array([0, 2, 4], dtype=object)

In [92]:
add_two_arrays = np.vectorize(add_elements)
add_two_arrays(np.arange(3), np.arange(3))

array([0, 2, 4])

# More Array Manipulation Techniques

## Methods for Linear Algebra
在 numpy.linalg 有實作許多線性代數運算的函數，可見[文件](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)。

In [93]:
# 求算反矩陣
from numpy.linalg import inv
X = np.random.randn(5, 5)
X

array([[-0.79286822, -1.83013593,  0.37534012, -0.89791052, -0.67126931],
       [-1.31006807,  1.04529744,  0.38149772,  0.49526838, -0.44541837],
       [ 1.05720178,  0.45910155,  1.38228976,  0.12602279, -1.28333013],
       [ 0.41439834, -0.48357616,  0.15740193,  0.52926209, -0.7244691 ],
       [ 1.45292723, -0.65844737, -0.63660986,  1.77023716,  0.57085566]])

In [94]:
X_inv = inv(X)
X_inv

array([[-0.2781152 , -0.49478234,  0.14662958,  0.23620323, -0.0836976 ],
       [-0.5223235 , -0.01420604, -0.04976977,  0.30595086, -0.34889112],
       [ 0.8313532 ,  0.54720027,  0.98774877, -2.18536979,  0.85165105],
       [ 0.17285545,  0.5240137 ,  0.08853325, -0.198649  ,  0.55905588],
       [ 0.49646721,  0.22817217,  0.39637492, -2.06935965,  0.77845955]])

## Concatenating Arrays
 - `np.concatenate()` 可合併 arrays，axis 可調整沿著結合的維度。
 - `np.vstack()` 等價於 np.concatenate([...], axis=0)
 - `np.hstack()` 等價於 np.concatenate([...], axis=1)

In [95]:
x1 = np.random.randn(2, 3)
x2 = np.random.randn(2, 3)

In [96]:
np.concatenate([x1, x2], axis=0)

array([[-1.15834337, -0.71364813,  1.15912407],
       [-0.44507651, -0.26641004,  0.33827227],
       [-0.83411888,  0.49058167,  1.72377107],
       [ 0.89673276,  1.36515632,  1.16803085]])

In [97]:
np.vstack([x1, x2])

array([[-1.15834337, -0.71364813,  1.15912407],
       [-0.44507651, -0.26641004,  0.33827227],
       [-0.83411888,  0.49058167,  1.72377107],
       [ 0.89673276,  1.36515632,  1.16803085]])

In [98]:
np.concatenate([x1, x2], axis=1)

array([[-1.15834337, -0.71364813,  1.15912407, -0.83411888,  0.49058167,
         1.72377107],
       [-0.44507651, -0.26641004,  0.33827227,  0.89673276,  1.36515632,
         1.16803085]])

In [99]:
np.hstack([x1, x2])

array([[-1.15834337, -0.71364813,  1.15912407, -0.83411888,  0.49058167,
         1.72377107],
       [-0.44507651, -0.26641004,  0.33827227,  0.89673276,  1.36515632,
         1.16803085]])

## Splitting Arrays
 - `np.split()` 可以分割一個 array 為多個小 arrays。indices_or_sections 為 1 維  array。 axis 可調整沿著分割的維度。分割的參數

In [100]:
X = np.random.randn(5, 3)
X

array([[-0.64200769,  0.10809585, -0.47740066],
       [ 0.88711305,  1.04191578, -0.57792554],
       [-2.36717157, -1.07007798, -0.48376739],
       [-0.09923082,  0.74750348,  1.20593428],
       [-1.1665229 ,  0.50858651,  1.42433025]])

In [101]:
np.split(X, [1, 3]) # 可將 indices_or_sections 內的值想成是每列間隔序數

[array([[-0.64200769,  0.10809585, -0.47740066]]),
 array([[ 0.88711305,  1.04191578, -0.57792554],
        [-2.36717157, -1.07007798, -0.48376739]]),
 array([[-0.09923082,  0.74750348,  1.20593428],
        [-1.1665229 ,  0.50858651,  1.42433025]])]

##  Repeat and Tile

`np.repeat()` 可複製 array 內的元素。

In [102]:
x = np.arange(3)
x.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [103]:
x.repeat([1, 2, 3])

array([0, 1, 1, 2, 2, 2])

In [104]:
X = np.random.randn(2, 2)
X.repeat(2, axis=0) 

array([[-2.08744057,  1.83193824],
       [-2.08744057,  1.83193824],
       [ 1.61632259,  1.91077023],
       [ 1.61632259,  1.91077023]])

`tile()` 複製的單位為一整個 array 

In [105]:
x = np.arange(3)
np.tile(x, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [106]:
X = np.random.randn(2, 2)
X

array([[ 0.13144714,  0.26785027],
       [-0.26363052,  0.45330634]])

In [107]:
# 可用一個 tuple 表示要複製生成的矩陣大小
# 如 (2, 2) 會產生一個 2x2 矩陣，而矩陣內的元素就是原本的 array
np.tile(X, (2, 2))

array([[ 0.13144714,  0.26785027,  0.13144714,  0.26785027],
       [-0.26363052,  0.45330634, -0.26363052,  0.45330634],
       [ 0.13144714,  0.26785027,  0.13144714,  0.26785027],
       [-0.26363052,  0.45330634, -0.26363052,  0.45330634]])

## Random Number Generation
NumPy 有提供亂數產生器的許多函數，可見[文件](https://docs.scipy.org/doc/numpy/reference/routines.random.html)。

In [108]:
# 使用 np.random.seed() 固定每次亂數產生器的結果
np.random.seed(1)
np.random.uniform(10)

6.246801957676833

In [109]:
np.random.seed(1)
np.random.uniform(10)

6.246801957676833

In [110]:
# 使用 np.random.RandomState() 固定每次亂數產生器的結果
rng1 = np.random.RandomState(1)
rng1.uniform(10)

6.246801957676833

In [111]:
rng2 = np.random.RandomState(1)
rng2.uniform(10)

6.246801957676833

## The `__array_interface__`

ndarray 有 `__array_interface__` 的屬性，如下例。 

In [112]:
arr = np.arange(5)
arr.__array_interface__

{'data': (140272271358080, False),
 'descr': [('', '<i8')],
 'shape': (5,),
 'strides': None,
 'typestr': '<i8',
 'version': 3}

屬性說明如下:
- data: 2-tuple, 第一個元素為指向資料的指標(整數或長整數)；第二個元素為記憶體是否唯讀
- typestr: 表示 ndarray 的型態
- shape: ndarray 的維度
- strides: ndarray 的 strides。說明見下方。
- version: array interface 的版本

shape, typestr 與 version 為必要屬性

`__array_interface__`  更多說明可見[此處](https://docs.scipy.org/doc/numpy/reference/arrays.interface.html)。

strides 為沿著某一維度由當前元素移動到下一個元素所需的 bytes。
以下面的例子來說，一個 float64 元素為 8 bytes。
- 從 (0, 0, 0) 移動到 (0, 0, 1) 需要 8 bytes。(左右移動)
- 從 (0, 0, 0) 移動到 (0, 1, 0) 需要 8 x 5 = 40 bytes。(上下移動)
- 從 (0, 0, 0) 移動到 (1, 0, 0) 需要 8 x 5 x 4 = 160 bytes。(矩陣間移動)

In [113]:
np.ones((3, 4, 5), dtype=np.float64)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

In [114]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)